apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - secrets.example.yaml
  - ingress.yaml
  - kafka/deployment.yaml
  - kafka/service.yaml
  - api-gateway/configmap.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/hpa.yaml
  - user-service/configmap.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - user-service/hpa.yaml
  - product-service/configmap.yaml
  - product-service/deployment.yaml
  - product-service/service.yaml
  - product-service/hpa.yaml
  - order-service/configmap.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - order-service/hpa.yaml
  - inventory-service/configmap.yaml
  - inventory-service/deployment.yaml
  - inventory-service/service.yaml
  - inventory-service/hpa.yaml
  - notification-service/configmap.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - notification-service/hpa.yaml
