apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: ecommerce
data:
  DB_URL: "jdbc:postgresql://ecommerce-postgres-dev.c2tmcgaiislf.us-east-1.rds.amazonaws.com:5432/inventory_db"
  DB_USERNAME: "postgres"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
